#!/bin/sh

#
# Installation script
#
# 1) cp mrkcoordload.config.default mrkcoordload.config
# 2) Install
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

# establish the config files
MAIN_CONFIG=mrkcoordload.config

# Make sure config file exists and source it
if [ -r ${MAIN_CONFIG} ]
then
    echo "Source ${MAIN_CONFIG}"
    . ${MAIN_CONFIG}
else
    echo "Cannot source configuration file: ${MAIN_CONFIG}"
    installFailed
fi

# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for each configuration file
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# Create the input directory if it doesn't exist.
#
if [ ! -d ${INPUTDIR} ]
then
    mkdir -p ${INPUTDIR}
fi

for c in assocload.config
do
. ${c}
${DLAINSTALL} ${DEV}
done

# If this installation is being done on lindon, create a symbolic link to
# the same input file path on hobbiton where the input file is published.
# The input directory should be locked down to protect the symbolic link.
#
if [ ${SERVER_NAME} = "lindon" ]
then
    rm -f ${INPUT_FILE_DEFAULT}
    ln -s /hobbiton${INPUT_FILE_DEFAULT} ${INPUT_FILE_DEFAULT}

    chmod -f 755 ${INPUTDIR}
fi

#
# If this installation is being done on hobbiton and the input file
# does not exist already, create one that is writable. This is just a
# place holder until an input file is published. The input directory
# should be opened up to allow the curation staff to publish new input
# files.
#
if [ ${SERVER_NAME} = "hobbiton" ]
then
    if [ ! -f ${INPUT_FILE_DEFAULT} ]
    then
        touch ${INPUT_FILE_DEFAULT}
        chmod 664 ${INPUT_FILE_DEFAULT}
        chgrp mgi ${INPUT_FILE_DEFAULT}
    fi

    chmod -f 775 ${INPUTDIR}
    chgrp mgi ${INPUTDIR}
fi

#
# The DLAInstall script removes all permissions from shell scripts for
# group "other" on non-development servers. The QC report wrapper
# script needs to have permissions restored on hobbiton to allow the
# curation staff to run it.
#
if [ ${SERVER_NAME} = "hobbiton" ]
then
    chmod -f 755 ${LOAD_QC_SH}
fi

exit 0

